#
# plugins.pro
#

TARGET = plugins
TEMPLATE = subdirs
CONFIG += ordered

!exists($$PWD/plugins.prf) {
    warning("plugins.pro: Missing plugins.prf, creating a default one")
    cfgLine("$$LITERAL_HASH Generated by plugins.pro")
    cfgLine("load(\"$$PWD/../lcdhost.prf\")")
}

load($$PWD/plugins.prf)
isEmpty(LH_PLUGINS_LIST): LH_PLUGINS_LIST=$$files(LH_*)

SUBDIRS += $$LH_PLUGINS_LIST
