#ifndef LH_MYLCDHOSTPLUGIN_GLOBAL_H
#define LH_MYLCDHOSTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LH_MYLCDHOSTPLUGIN_LIBRARY)
#  define LH_MYLCDHOSTPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LH_MYLCDHOSTPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LH_MYLCDHOSTPLUGIN_GLOBAL_H
